id: P82FB3D97
initial_creation_type: input
source_metadata:
  title: Dzogchen Series
  language: it
  description: 'The following texts are available as part of our Dzogchen (rdzogs
    chen) or Great Perfection series:'
  volume:
    8614bcb52e9d4d90a42ff74c471f9674:
      title: Advice for Hor Özer
      parent: Advice
    36bf3d0f269541329bbea03e425ec891:
      title: Advice for Palseng
      parent: Advice
    47a51649830a43f8ac073d65918fd95f:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    1ae904585f7640008c3423e378b77ef9:
      title: Advice for Garje Khamtrul Rinpoche
      parent: Advice
    1252153e68c14c4d94ca3bed196e48e8:
      title: Advice on Recognizing the Nature of Mind
      parent: Advice
    8eac8c7ad9a0444393dd3c2f83b0bbd0:
      title: 'Advice: Emptying the Three Realms of Existence'
      parent: Advice
    7bbfabed1f4f4d3384238930e06f3b3b:
      title: An Instruction on the Great Perfection
      parent: Advice
    8dea11bf96c145088eee558dc1551f02:
      title: Brief Dzogchen Instruction
      parent: Advice
    cd1ccab668ad4e2c9ca082875a13b3d5:
      title: Direct Instruction
      parent: Advice
    1b3ec237cdfd474da5ee6103a80f3c67:
      title: Summary of the Key Points of Advice on Trekchö
      parent: Advice
    9fbbfa37351f4799b524e12a89a6ac2f:
      title: Vajra Verses on the Natural State
      parent: Advice
    4793d554447d43fbb5b7a36aaf13be2a:
      title: Advice for a King
      parent: Advice
    4c32e8263fd945ba8e053cf4c77d3c59:
      title: A Song of Advice for Gok Zangden
      parent: Advice
    f88ebba3bd4c49d5ad1491520dee87d6:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Advice
    bfe02fd9eb184aaa8455d7c5810595ac:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Advice
    4573f3ffbe034328a845c69a3c02815b:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Advice
    bbaa6aa856d643b1a1658a0d3658f703:
      title: 'Vomiting Gold: A Pith Instruction in the Form of Advice for the Diligent
        Practitioner, the Excellent Atsang'
      parent: Advice
    8b18a00f58be4a36ab8a3556ff69832f:
      title: A Liberating Reminder
      parent: Advice
    0ce960b49fdc45848bd9098575202cf3:
      title: 'A Mirror Revealing the Crucial Points: Advice on the Ultimate Meaning'
      parent: Advice
    70b40e60148645499a3d589a2978fb54:
      title: 'A Wish-Fulfilling Gem: Guidance on the Meaning of Being at Ease with
        Illusion, A Dzogchen Teaching'
      parent: Advice
    84af3f4ede8841099aa5b4ad80e5ab6c:
      title: 'From ''Finding Comfort and Ease in Meditation'': A Guide to Locations
        for Cultivating Samadhi'
      parent: Advice
    3088963fce3f4dc1919d01bab8ccab7b:
      title: 'From ''Finding Comfort and Ease in Meditation'': The Practitioner of
        Meditation'
      parent: Advice
    7b6d622327da4229b07edabca8e98bfe:
      title: 'A Lamp to Dispel Darkness: An Instruction that Points Directly to the
        Very Essence of Mind in the Tradition of ‘the Old Realized Ones’'
      parent: Advice
    a2c26c67352c41d982bfbe424826aa9b:
      title: Pith Instruction on the Three Crucial Statements
      parent: Advice
    d3d25a387d7640e3a0aafd024fd37b86:
      title: The Essence of Mind
      parent: Advice
    b79efb5a19f04a81b16dfdd8741ed001:
      title: 'The Essence of Wisdom: How to Sustain the Face of Rigpa'
      parent: Advice
    b620baecfba34b949bcd1c050b1b7472:
      title: The Key Points of Trekchö
      parent: Advice
    3dd42d5c8ae24cf7b84a66bc580e9d03:
      title: The Nature of Mind
      parent: Advice
    5874f199e2724f69a41cf3d31d5b23c9:
      title: Advice on the View, Meditation, Action and Fruition
      parent: Advice
    19e2ca3e8b1f4e5eab58a030d0b8cb4a:
      title: The Pointing-the-Staff Instruction
      parent: Advice
    dd0e7048b0d4421dadf42cf0f8cec56c:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Advice
    24e9404228fc46f49788ee81234910db:
      title: Principles of the Dzogchen Practice of Khordé Rushen
      parent: Advice
    fc2cd0d5184c486996b77718eb891d0d:
      title: The Five Wisdoms
      parent: Advice
    09fb414e5ced45f4bccb6cf3daf61946:
      title: Advice on How to Put the Meaning of the Natural Great Perfection into
        Practice
      parent: Advice
    4332f7f8ccff49b09983b3a4766d7482:
      title: 'Self-Liberating Meditation: A Profound Method for Attaining Enlightenment
        according to the Ultimate Great Perfection'
      parent: Advice
    7ddd55564b70433d8f1e0cb7ed1bb71c:
      title: Advice from the Lips of Tertön Sogyal
      parent: Advice
    0ba23507097b428aa77e0125afd83211:
      title: A Torch to Illuminate Crucial Points of the Path of Meditation
      parent: Advice
    9d82ca81548145a99ba6801abf76c876:
      title: The Four Uncommon Samayas of the Great Perfection
      parent: Advice
    fc46bd4f2a2b4c92981fdb18c8525f1f:
      title: A Brief Presentation of View, Meditation and Action
      parent: Advice
    2a06e1ac9fef4074ba219b3d23948882:
      title: From the Oral Tradition of the Lama of Nyarong
      parent: Advice
    68c9bfdb8fd1427798814dd0eee37f14:
      title: On the Final Words of Orgyen Tendzin Norbu
      parent: Commentaries
    b28a54489afc455fb3567d9b553a0170:
      title: 'The Precious Jewelled Key: A Synopsis of the Aspiration of the Great
        Perfection Mañjuśrī'
      parent: Commentaries
    de637304098244a8a6f737f5c8407ec5:
      title: 'The Prayer of the Ground, Path & Fruition from the Heart-Essence of
        the Vast Expanse:'
      parent: Commentaries
    1fa52df3e05943efb8c1a0a3d6732094:
      title: Commentary on Vajra Verses on the Natural State
      parent: Commentaries
    962b69ba30f143cb9d4ab8d629b4b949:
      title: Prayer to the Gurus of the Dzogchen Lineage
      parent: Lineage Prayers
    f17c6aec8c184220b9dd3a074a8e4fff:
      title: A Prayer to Shower Down the Rain of Wisdom
      parent: Lineage Prayers
    a3988b0f5802422cb19d384f6a419707:
      title: How to Count the Four Permutations of Actual and Basis
      parent: Notes
    8e6cf90139a1454bae045a62ddff7455:
      title: Commentary on Some Terms from the Great Perfection
      parent: Notes
    897c909956cb4507a637f76fefbf7abd:
      title: Brief Explanation of Clarification and Transcendental Resolution from
        the Oral Tradition of Nyala Sogyal
      parent: Notes
    99433441f9684bfb8cf95a4b66f28edd:
      title: How Liberation and Delusion Develop Out of the Clear Light of the Ground,
        etc.
      parent: Notes
    7744144c17e34d799b3b90bef2296520:
      title: Notes from the Oral Tradition on Ālaya, Ālaya Consciousness, etc.
      parent: Notes
    c6f9cc9108a749b3ad52c115a154c466:
      title: Dzogchen Aspiration Prayer
      parent: Prayers
    ffd9970cec6d4e72a7afc4c77c712198:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Prayers
    7c13b8efea584e859919250e4691efc7:
      title: A Dzogchen Tögal Prayer
      parent: Prayers
    bd1cfb26f34e431592eebe315bfbb393:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Prayers
    b049fbe36ce44f6b9ab4ab56a052f79b:
      title: 'The Pure Three Kāyas Ablaze in Perfect Splendour: A Prayer Based on
        the Meaning of the Great Perfection'
      parent: Prayers
    c3755b8a336942f5ade7a937dbca3d93:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Prayers
    8a582aa7d30c4e81b5ef8895c8235e4d:
      title: Prayer to Nyala Pema Dündul
      parent: Prayers
    bce2b634e9864372aab49edbdfd726ab:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Prayers
    c10eb167bf19425198d6df11bc0c1211:
      title: The Song of the Vajra
      parent: Songs
    2a319e05bf414258bc7e6d337ffaf416:
      title: A Song in Six Verses
      parent: Songs
    176d9467f11f4b5fa831f9f18a3e6e8b:
      title: Song of Experiential Certainty
      parent: Songs
    2db5c606dfe44ed8b91aa89e0f94ad6d:
      title: Spontaneously Written Song of Experience
      parent: Songs
    702f310a2d97405da84d2d4ceb1a5e24:
      title: In This Pure Awareness
      parent: Songs
    be75a477bc1641149bbe2171b5c4dd12:
      title: 'Aho Ye: Impressions of an Insightful Experience'
      parent: Songs
    59baa327258c46a582584aeb0b10552b:
      title: Five-Verse Doha of Yogic Realization
      parent: Songs
    85ab6b99d48247f392b5622bccf16130:
      title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin
        Nyima
      parent: Testament
created_at: '2022-03-01T03:36:31.996890'
last_modified_at: '2022-03-01T03:36:31.996893'
